// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChHhS4_m0-KDA1DsftX6ivG5c-KfDo_7Y',
    appId: '1:105786781364:web:ba745b26f9b435b425b1e1',
    messagingSenderId: '105786781364',
    projectId: 'flash-chat-1d6d9',
    authDomain: 'flash-chat-1d6d9.firebaseapp.com',
    storageBucket: 'flash-chat-1d6d9.appspot.com',
    measurementId: 'G-JMEEFV7RVK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjVvbWYU7xUkCbNQ8WUa1YeHD6ZSfbOAs',
    appId: '1:105786781364:android:959ba7010cbe56df25b1e1',
    messagingSenderId: '105786781364',
    projectId: 'flash-chat-1d6d9',
    storageBucket: 'flash-chat-1d6d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRYGO5SbiOpUQtDu_P__ifdMjTc7Qptbo',
    appId: '1:105786781364:ios:6dbc003e27c0d46b25b1e1',
    messagingSenderId: '105786781364',
    projectId: 'flash-chat-1d6d9',
    storageBucket: 'flash-chat-1d6d9.appspot.com',
    iosClientId: '105786781364-c838f0moh84kcrqr4ddogh7ssje7la76.apps.googleusercontent.com',
    iosBundleId: 'com.example.groupChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRYGO5SbiOpUQtDu_P__ifdMjTc7Qptbo',
    appId: '1:105786781364:ios:6dbc003e27c0d46b25b1e1',
    messagingSenderId: '105786781364',
    projectId: 'flash-chat-1d6d9',
    storageBucket: 'flash-chat-1d6d9.appspot.com',
    iosClientId: '105786781364-c838f0moh84kcrqr4ddogh7ssje7la76.apps.googleusercontent.com',
    iosBundleId: 'com.example.groupChatApp',
  );
}
